config/routes.rb
Rails.application.routes.draw do

  get    '/coxinhas/getCoxinhas', to: 'coxinhas#getCoxinhas', via: [:get, :post]
  post   '/coxinhas/setCoxinha', to: 'coxinhas#setCoxinha', via: :post
  resources :coxinhas

end

app/models/coxinha.rb
class Coxinha < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/coxinhas_controller.rb
class CoxinhasController < ApplicationController
  before_action :set_coxinha, only: [:show, :edit, :update, :destroy]

  # GET /coxinhas
  # GET /coxinhas.json
  def index
    @coxinhas = Coxinha.all
  end

  def getCoxinhas
    @coxinhas = Coxinha.all
    render json: @coxinhas
  end

  def setCoxinha
    @coxinha = Coxinha.new(coxinha_params)
    if @coxinha.save
      render json: ['Cadastrado com sucesso!', @coxinha]
    else
      render json: ['falhou', @coxinha.errors]
    end
  end

  # GET /coxinhas/1
  # GET /coxinhas/1.json
  def show
  end

  # GET /coxinhas/new
  def new
    @coxinha = Coxinha.new
  end

  # GET /coxinhas/1/edit
  def edit
  end

  # POST /coxinhas
  # POST /coxinhas.json
  def create
    #@coxinha = request.body.read
    @coxinha = Coxinha.new(coxinha_params)

    respond_to do |format|
      if @coxinha.save
        format.html { redirect_to @coxinha, notice: 'Coxinha was successfully created.' }
        format.json { render json: @coxinha }
      else
        format.html { render :new }
        format.json { render json: @coxinha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coxinhas/1
  # PATCH/PUT /coxinhas/1.json
  def update
    respond_to do |format|
      if @coxinha.update(coxinha_params)
        format.html { redirect_to @coxinha, notice: 'Coxinha was successfully updated.' }
        format.json { render :show, status: :ok, location: @coxinha }
      else
        format.html { render :edit }
        format.json { render json: @coxinha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coxinhas/1
  # DELETE /coxinhas/1.json
  def destroy
    @coxinha.destroy
    respond_to do |format|
      format.html { redirect_to coxinhas_url, notice: 'Coxinha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coxinha
      @coxinha = Coxinha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coxinha_params
      params.require(:coxinha).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coxinhas_helper.rb
module CoxinhasHelper
end

app/views/coxinhas/_form.html.erb
<%= form_for(@coxinha) do |f| %>
  <% if @coxinha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coxinha.errors.count, "error") %> prohibited this coxinha from being saved:</h2>

      <ul>
      <% @coxinha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coxinhas/edit.html.erb
<h1>Editing Coxinha</h1>

<%= render 'form' %>

<%= link_to 'Show', @coxinha %> |
<%= link_to 'Back', coxinhas_path %>

app/views/coxinhas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coxinhas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coxinhas.each do |coxinha| %>
      <tr>
        <td><%= coxinha.id %></td>
        <td><%= coxinha.name %></td>
        <td><%= link_to 'Show', coxinha %></td>
        <td><%= link_to 'Edit', edit_coxinha_path(coxinha) %></td>
        <td><%= link_to 'Destroy', coxinha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coxinha', new_coxinha_path %>

app/views/coxinhas/new.html.erb
<h1>New Coxinha</h1>

<%= render 'form' %>

<%= link_to 'Back', coxinhas_path %>

app/views/coxinhas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coxinha.name %>
</p>

<%= link_to 'Edit', edit_coxinha_path(@coxinha) %> |
<%= link_to 'Back', coxinhas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebScript</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>